#

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv(r"C:\Users\udayk\Downloads\iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
dummies=pd.get_dummies(df['species'])
dummies.head

<bound method NDFrame.head of      setosa  versicolor  virginica
0      True       False      False
1      True       False      False
2      True       False      False
3      True       False      False
4      True       False      False
..      ...         ...        ...
145   False       False       True
146   False       False       True
147   False       False       True
148   False       False       True
149   False       False       True

[150 rows x 3 columns]>

In [10]:
merged= pd.concat([df,dummies], axis='columns')
merged.head()

,sepal_length,sepal_width,petal_length,petal_width,species,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,setosa,True,False,False
1,4.9,3.0,1.4,0.2,setosa,True,False,False
2,4.7,3.2,1.3,0.2,setosa,True,False,False
3,4.6,3.1,1.5,0.2,setosa,True,False,False
4,5.0,3.6,1.4,0.2,setosa,True,False,False

In [12]:
final= merged.drop(['species'], axis='columns')
final.head()

,sepal_length,sepal_width,petal_length,petal_width,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False

In [14]:
from sklearn.model_selection import train_test_split

In [20]:
final.replace({True: 1, False: 0}, inplace=True)

final

C:\Users\udayk\AppData\Local\Temp\ipykernel_21828\3005068206.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final.replace({True: 1, False: 0}, inplace=True)

,sepal_length,sepal_width,petal_length,petal_width,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [22]:
X = final[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = final[['setosa', 'versicolor','virginica']]

In [24]:
from sklearn.model_selection import train_test_split

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [28]:
X_test

     sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4
31            5.4          3.4           1.5          0.4
64            5.6          2.9           3.6          1.3
141           6.9          3.1           5.1          2.3
68            6.2          2.2           4.5          1.5
82            5.8          2.7           3.9          1.2
110           6.5          3.2           5.1          2.0
12            4.8          3.0           1.4          0.1
36            5.5          3.5           1.3          0.2
9             4.9          3.1           1.5          0.1
19            5.1          3.8           1.5          0.3
56            6.3          3.3           4.7          1.6
104           6.5          3.0           5.8          2.2
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
132           6.4          2.8           5.6          2.2
29            4.7          3.2           1.6          0.2
127           6.1          3.0           4.9          1.8
26            5.0          3.4           1.6          0.4
128           6.4          2.8           5.6          2.1
131           7.9          3.8           6.4          2.0
145           6.7          3.0           5.2          2.3
108           6.7          2.5           5.8          1.8
143           6.8          3.2           5.9          2.3
45            4.8          3.0           1.4          0.3
30            4.8          3.1           1.6          0.2

In [32]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='ovr', max_iter=200)
model.fit(X_train, y_train)

ValueError: y should be a 1d array, got an array of shape (120, 3) instead.

In [148]:
model.fit(X_test,y_test)

ValueError: y should be a 1d array, got an array of shape (30, 3) instead.

In [ ]:
# unable to understand why not able to do the regression . solving as youtube vedio in multiclassification logistic regression 2